version: "3"

services:
  nextcloud-db:
    image: docker.io/library/mariadb:lts
    container_name: nextcloud-db
    hostname: nextcloud-db
    restart: unless-stopped
    networks:
      nextcloud-net:
        ipv4_address: 10.0.1.2
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - TZ=America/Los_Angeles
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud_pass
      - MYSQL_ROOT_PASSWORD=nextcloud_pass
  nextcloud:
    depends_on:
      - nextcloud_db
    image: docker.io/library/nextcloud:stable-apache
    container_name: nextcloud
    hostname: nextcloud
    restart: unless-stopped
    networks:
      nextcloud-net:
        ipv4_address: 10.0.1.3
    ports:
      - 8080:80
    volumes:
      - nextcloud-app:/var/www/html
      - nextcloud-data:/var/www/html/data
    environment:
      - MYSQL_DATABASE=nextcloud-db.dns.podman
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=DB_USER_PASSWORD
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud_pass

volumes:
  nextcloud-db:
    name: nextcloud-db
  nextcloud-app:
    name: nextcloud-app
  nextcloud-data:
    name: nextcloud-data

networks:
  nextcloud-net:
    name: nextcloud-net
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
